CliMA/SurfaceFluxes.jl

Project.toml
src/SurfaceFluxes.jl

We're not currently using Thermodynamics, so let's remove it as a dependency. This PR also bumps the version for a new release.

Remove unnecessary Thermodynamics dep, bump version

---

.buildkite/pipeline.yml
.github/workflows/ci.yml
Project.toml
src/SurfaceFluxes.jl
test/Project.toml

No interface changes, but the resolver is resulting in issues for julia 1.5, so let's just drop support. Many Clima packages require 1.7 or higher anyway, so there's not much gain in maintaining support for julia 1.5.

Upgrade to latest Thermodynamics

---

Project.toml
src/SurfaceFluxes.jl

This PR widens the input types to Real, so that we can ForwardDiff through SurfaceFluxes.

Widen input types to Real

---

src/UniversalFunctions.jl
test/test_universal_functions.jl

This PR. Decouples the universal function parameters, which all fell back to Businger. This was originally done to avoid code duplication. Some universal functions developed, for example in Gryanik et al., focused on positive regions of ζ (see eq. 13 in `New modified and extended stability functions for the stable boundary layer based on SHEBA and parametrizations of bulk transfer coefficients for climate models`). Being that this work built on-top of Businger, it seems most natural to use the Businger results when ζ is negative, which is what is now hard-coded here.
This will allow us to more easily update our clima parameters

Decouple universal functions

---

src/SurfaceFluxes.jl
test/runtests.jl

Divisions by LMO appear in the equation sets, and result in NaN / nonsensical values in some scenarious. This PR adds a function that catches such cases. 
cc @yairchn @szy21 @jiahe23 
Benefits: Prevents NaNs with near zero LMO 
Risks: Empirical addition of epsilon perturbation.

Fix for near-zero LMO values

---

src/SurfaceFluxes.jl
test/runtests.jl

- Modify buoyancy scale function to use virtual dry static energy (`DSE_v`). 
- Update neutral stability functions for `C_h` (heat exchange coefficient)
- Include prints for `z0` and `dz` in scenario with unconverged surface fluxes.

use virtual dry static energy instead of density

---

src/SurfaceFluxes.jl

We found that in neutral conditions `Inf * sign(0) = NaN` so that `ΔDSEᵥ` needs to be protected from zeros. We added s some zero protection to buoyancy flux and buoyancy star as well

add non_zero protection for LMO and bfluxes

---

src/SurfaceFluxes.jl

the current tol_neutral of `cd/10` is found to be too insensitive for connective BL runs where the theta profile is almost neutral `ΔDSEᵥ ~ 100` and strong surface heat fluxes are imposed.

reduce the tol_neutral to cd/100

---

parameters/create_parameters.jl
src/Parameters.jl
src/SurfaceFluxes.jl
src/UniversalFunctions.jl
test/runtests.jl
test/test_convergence.jl

Following Gryanik et al. (2021) DOI: 10.1029/2021MS002590, we include a non-iterative solution for stability parameter ζ (and therefore Monin-Obukhov length) in cases where ζ >= 0. Design documentation has been updated. 
1. Neutral b.l. tolerance is specified at just one point now (via user interface function `surface_conditions`). Value is kept at cp_d/100 following PR#66.  
2. Keyword argument added to `surface_conditions` to allow user to select whether they want to use the non-iterative procedure specified above. 
3. For stability functions which are only for zeta >= 0, Businger-Dyer functions are applied as the default option in cases with ζ <= 0. 
4. Adds convergence checks for the `Gryanik` and `Grachev` type universal functions. 
Optional removal of dependence on user specified …

Non-iterative solution for stability parameter in stable boundary layers

---

src/SurfaceFluxes.jl
test/runtests.jl
test/test_convergence.jl

Towards improving test coverage in SurfaceFluxes.jl - this PR adds consistency checks for sign conventions in momentum and buoyancy fluxes, evaporation, and L_MO. 
#73 
----

Add consistency checks for output flux and b.l. stability conventions 

---

src/SurfaceFluxes.jl

Cleans up interfaces through function call 
modified:   src/SurfaceFluxes.jl
Replaces the field access for interior grid level with a function. 
Towards changes in RSL models + updated tests in recovery profiles. 
----

Replace z_in access in profile recovery function

---

Project.toml

(1) \beta (evaporation exchange coefficient) kwarg introduced in #75
modified:   Project.toml
Minor Release v0.5.0
----

Bump minor version: v0.5.0

---

src/SurfaceFluxes.jl

Try to fix #62 and ClimaAtmos [#1225](https://github.com/CliMA/ClimaAtmos.jl/issues/1225)
----

use relative or absolute tolerance for obukhov length

---

docs/src/SurfaceFluxes.md

Documentation PR for the modification of evapotranspiration through conductance networks. 
Reference: Ch 7 (Bonan textbook) 
Linked issue: #85 
Closes #88

Docs: conductance networks for evapotranspiration

---

src/SurfaceFluxes.jl

Currently SurfaceFluxes breaks some of the EDMF cases in ClimaAtmos. I don't think it is a problem with SurfaceFluxes, but I would like to upgrade the dependencies in ClimaAtmos. Therefore I'm changing the initial guess of L_MO back to the default -1. cc @akshaysridhar 
----

Change initial guess of L_MO to -1

---

src/SurfaceFluxes.jl

This PR just changes the `evaporation` function to calculate `hv_sfc = TD.latent_heat_vapor(param_set, T_0)` instead of `hv_sfc = cp_v * (T_sfc - T_0) + Lv_0`. These are equivalent, but the new calculation uses the Thermodynamics function instead.

Change evaporation function to use Thermodynamics function

---

Project.toml
test/Project.toml

This PR widens the KernelAbstractions (KA) compat range to include version KA 0.9 so that ClimaAtmos can update from CUDA 4.0.1 to 4.2.0:
```
julia> Pkg.add(Pkg.PackageSpec(;name="CUDA", version="4.2.0"))
Updating registry at `~/.julia/registries/General.toml`
Resolving package versions...
ERROR: Unsatisfiable requirements detected for package KernelAbstractions [63c18a36]:
KernelAbstractions [63c18a36] log:
├─possible versions are: 0.1.0-0.9.4 or uninstalled
├─restricted by compatibility requirements with Thermodynamics [b60c26fb] to versions: 0.7.0-0.9.4
│ └─Thermodynamics [b60c26fb] log:
│   ├─possible versions are: 0.2.0-0.10.2 or uninstalled
│   └─restricted to versions 0.10 by ClimaAtmos [b2c96348], leaving only versions 0.10.0-0.10.2
│     └─ClimaAtmos [b2c96348] log:
│ …
```

Widen KernelAbstractions compat range

---

docs/bibliography.bib
docs/src/SurfaceFluxes.md

modified:   SurfaceFluxes.md
Improve documentation. 
----

Fix equation rendering in docs

---

Project.toml

We are still running some of our ci on Julia 1.8 in ClimaAtmos. So we can't restrict SurfaceFluxes to 1.9

bump down compat req. for Julia

---

Project.toml
src/SurfaceFluxes.jl
test/Project.toml
test/runtests.jl
test/test_convergence.jl
test/test_profiles.jl

StaticArrays support left-over from ClimateMachine.
This is unnecessary within the SurfaceFluxes package. Removes dependence on StaticArrays and updates tests to use tuples.

Remove dependence on StaticArrays

---

.github/workflows/docs.yml

Documentation might have not been pushed without this.

Restore documentation

---

.buildkite/pipeline.yml
Project.toml
README.md
src/SurfaceFluxes.jl

As of CUDA 5.1.1, there are some issues with ClimaAtmos and Julia 1.10.
It seems that the issue is with this particular function and the error
is due to added calles to gc_frame functions that cannot be compiled on
a GPU.
For unknown reasons, the code compiles when we remove the keyword
arguments. While the issue is being investigated, we can work around it
by excluding the offending branch
Includes house cleaning.

Hide code branch that leads to GPU incompatibilities in Julia 1.10

---

test/aqua.jl

This PR switches to using `test_all` and some kwargs to opt out of the unbound args and ambiguities tests.

Fix aqua tests

---

Project.toml
test/Project.toml
test/aqua.jl
test/test_convergence.jl

This PR fixes an issue where the param set with the wrong float type was being passed in to tests. I'm not sure how this was passing before.
I also commented out a portion of an Aqua test that is only meant to be uncommented for debugging (unbound args).

Update to ClimaParameter v0.9.0, Thermodynamics v0.12.0

---

Project.toml
src/Parameters.jl
src/SurfaceFluxes.jl

This PR is a followup to CliMA/RootSolvers.jl#50, CliMA/Thermodynamics.jl#199, and CliMA/Thermodynamics.jl#200. Together with those changes, this should allow us to pass `ForwardDiff.Dual` numbers through the ClimaAtmos implicit tendency.
- Remove unused `FT` type variables from method definitions
- Drop typecasts to `FT` where the argument is derived from the parameter set
- For typecasts to `FT` where the argument is a `Float64` literal (`0.01` or `Inf`), infer `FT` from the parameter set instead of the surface conditions (which might contain a mixture of ordinary numbers and `Dual` numbers)
- Add a restriction to the definition of `SurfaceFluxesParameters` to ensure that the parameter set has an internally consistent `FT` type
- Add a constructor to `SurfaceFluxConditions` that …

Remove unnecessary typecasts and add promotion to support Dual numbers

---

.buildkite/pipeline.yml

Moving buildkite to the new partitions.

Try using expansion/gpu queues

---

Project.toml
src/SurfaceFluxes.jl

It looks like the fix to #144 applied in #157 did not work in ClimaAtmos (see [this build](https://buildkite.com/clima/climaatmos-ci/builds/16849)), and several test cases now have a garbage collection instruction that is breaking GPU compilation. Replacing `kwargs` in some methods of the `obukhov_length` function with regular `args` fixes this issue. Since these are internal methods, they probably shouldn't have `kwargs` anyway.
----

Fix kwargs issue on GPUs

---

Project.toml
src/SurfaceFluxes.jl

Updates following section 3.6.4 in the dycore paper.
Tests work for me locally when using the Thermodynamics v0.13 branch. This PR should be merged after we do the Thermodynamics release.
cc: @kmdeck - will it affect the land models?

Dycore paper updates in how we compute SHF and LHF

---

.buildkite/pipeline.yml

🤖 Beep boop. I am GabrieleBOT. 🤖
I received an update so that I can inform you directly of the changes (but feel free to check the [release notes](https://github.com/CliMA/ClimaModules/blob/main/NEWS.md)).
The most recent version of climacommon uses the newly released Julia 1.11.0.

Update climacommon to 2024_10_09
