- .dev/Project.toml
- .github/workflows/CodeCov.yml
- .github/workflows/JuliaFormatter.yml
- .github/workflows/ci.yml
- .github/workflows/docs.yml
Run on Julia 1.7.2, and upgrade formatter
> Upgrade to latest julia version

- docs/src/UniversalFunctions.md
- docs/src/plot_universal_functions.jl
This PR moves the docs example into a script.
> Move docs example into script

- src/Parameters.jl
> Define broadcastable for parameters

- src/SurfaceFluxes.jl
I am adding here evaporation to the output `surface conditions` and adding `Δρ` to the condition for neural BL in the heat flux function
> add evap to output, add density to condition

- Project.toml
- src/SurfaceFluxes.jl
Uncomments docstrings for function compute u_star, adds doc providing clarity on LMO tolerance. Bump minor version.
> Uncomment u_star docstrings + bump minor version

- Project.toml
> Minor version bump

- src/SurfaceFluxes.jl
- test/runtests.jl
(Clearly and concisely state the purpose of this PR)
(State concisely the benefits to be derived from and the risks associated with this PR)
(Provide references to any link issues. Use closes #issuenum to automatically close an open issue)
- Fixes #
- Closes #
> protect bstar in denominator

- src/SurfaceFluxes.jl
- test/runtests.jl
- test/test_convergence.jl
(1) Remove @show statements
(2) Update solver function to avoid entering iterative loop in neutral
conditions
(3) Update exchange coefficients to avoid iterative loop in neutral
conditions
(4) Update convergence coverage checks to maintain physically reasonable ratio of z0m/z0b
(5) Return FT(Inf) in neutral conditions
modified:   src/SurfaceFluxes.jl
modified:   test/runtests.jl
modified:   test/test_convergence.jl
+ Format
Refactors test (add F64 checks), removes unnecessary function imports from Thermodynamics->TestedProfiles, clears code duplication,re-enable GPU checks, increase coverage of convergence checks. 
Risks: Package requires further physics checks and tests in breaking edge cases ("data-tests" similar to Thermodynamics.jl will be added when such cases are discovered in …
> remove @show and make print conditional

- Project.toml
Minor release following NaN protection for buoyancy flux functions and Monin-Obukhov length in neutral conditions.
> Bump minor version 0.4.4 -> 0.4.5

- src/SurfaceFluxes.jl
Update convergence tolerance to relate it to first grid space (generalises to cases with non-zero surface elevation)
Update output to include thermodynamic states. 
modified:   src/SurfaceFluxes.jl
> Output thermo state; grid spacing generalisation in tolerances

- Project.toml
> Update minor version

- .buildkite/pipeline.yml
- .github/workflows/CodeCov.yml
- .github/workflows/JuliaFormatter.yml
- .github/workflows/ci.yml
- .github/workflows/docs.yml
- Project.toml
- src/SurfaceFluxes.jl
- test/Project.toml
- test/test_convergence.jl
- test/test_profiles.jl
This PR:
- Upgrades to Julia 1.8
- Widens some compat ranges so that we can upgrade dependencies
> Upgrade to julia 1.8, widen compat ranges

- src/SurfaceFluxes.jl
Co-authoured-by: @LenkaNovak @kmdeck 
Adds a beta factor to evaporation when surface condition is `ValuesOnly` or `Coefficients` to account for surface resistance. 
----
> Add beta factor to evaporation

- src/SurfaceFluxes.jl
Fixes the argument order bug introduced in #78. Also slightly increase the relative tolerance.
----
> fix an error in tolerance argument

- Project.toml
Update patch version to v0.5.1.
----
> Update patch version

- src/SurfaceFluxes.jl
> Make initial guess of l_mo dependent on stability regimes

- docs/src/SurfaceFluxes.md
Add documentation from design-docs (Overleaf) 
Methods - 
(1) Physick and Garratt (1995) 
(2) Wang and Iacono (2007)
(3) Bonan et al. (2018)
> RSL model documentation

- docs/src/UniversalFunctions.md
- docs/src/plot_universal_functions.jl
Add plots reproducing Figs 6.3(a),(b) from [Bonan (2019)](https://doi.org/10.1017/9781107339217.007) to existing documentation.
----
> Add Bonan plots to documentation

- test/test_universal_functions.jl
Add edge case tests for [Gryanik (2021)](https://doi.org/10.1029/2021MS002590) Eq. 2 and Eq. 3 to existing test set.
----
> Added tests for GLSG21 Eq. 2 and Eq. 3

- docs/src/UniversalFunctions.md
Add the full set of universal functions implemented in ```UniversalFunctions.jl``` to existing docs, reproducing [this visual tabulation](https://docs.google.com/document/d/1T2krlLtTR-WMaMpYOvUqlcOWm2GK3-P5tluCzHc9ibg/edit?usp=sharing).
----
> Add Comprehensive Set of Universal Functions to Docs

- docs/bibliography.bib
- docs/src/index.md
- docs/src/plot_universal_functions.jl
- parameters/create_parameters.jl
- src/UniversalFunctions.jl
- test/test_convergence.jl
- test/test_universal_functions.jl
Add stability correction functions from Beljaars and Holtslag (1991) into ```UniversalFunctions.jl```.
Here is a [visual tabulation](https://docs.google.com/document/d/1T2krlLtTR-WMaMpYOvUqlcOWm2GK3-P5tluCzHc9ibg/edit?usp=sharing) of the equations in ```UniversalFunctions.jl``` for ease of reference.
----
> Implementation of Beljaars SCFs

- src/SurfaceFluxes.jl
> Fix type parameter

- src/SurfaceFluxes.jl
Simplify `non_zero` function
----
> Update non-zero function

- .buildkite/pipeline.yml
- Project.toml
- src/SurfaceFluxes.jl
- test/Project.toml
- test/runtests.jl
- test/runtests_gpu.jl
- test/test_convergence.jl
- test/test_universal_functions.jl
Re-introduce GPU tests. Demonstrate compatibility of higher-level function with GPUs.
> Add GPU tests

- docs/src/plot_bonan_profiles.jl
- src/SurfaceFluxes.jl
- test/runtests.jl
- test/test_convergence.jl
FDScheme > PointValueScheme
FVScheme > LayerAverageScheme.
> Fix method type names for clarity. 

- Project.toml
- src/SurfaceFluxes.jl
Update version 0.7.2 > 0.8.0. Towards new release - introduces breaking changes!
modified:   Project.toml
modified:   src/SurfaceFluxes.jl
> Update default scheme, update package version. 

- .github/workflows/CodeCov.yml
- .github/workflows/JuliaFormatter.yml
- .github/workflows/ci.yml
- .github/workflows/docs.yml
> Always run CI on PRs

- bors.toml
Bors is gone. Delete bors.toml
> Remove bors toml file. 

- src/SurfaceFluxes.jl
> Fix a minor typo in a docstring

- test/runtests_gpu.jl
> Use global index to fix GPU output

- Project.toml
- docs/Project.toml
- docs/src/index.md
- docs/src/plot_bonan_profiles.jl
- docs/src/plot_universal_functions.jl
- ext/CreateParametersExt.jl
- test/Project.toml
- test/runtests.jl
- test/runtests_gpu.jl
- test/test_cases.jl
- test/test_convergence.jl
- test/test_universal_functions.jl
This PR updates to the new package once it has been released. Depends on Thermodynamics releasing a new patch version first.
> Update to ClimaParams v0.10

- Project.toml
> Fixes compat entry for RootSolvers.jl

- src/SurfaceFluxes.jl
- src/UniversalFunctions.jl
Changes the non_zero function to preserve the sign of the input. Also cleans up universal functions to make the logic more clear.
----
> change non_zero function and clean up

- Project.toml
- test/Project.toml
Bump ClimaParams, RootSolvers, and Theromdynamics upper compats
Update version patch
----
> Make patch with new upper compats

- Project.toml
- src/Parameters.jl
- src/SurfaceFluxes.jl
Bump ClimaParams and Theromdynamics upper compats
----
> bump patch version

- Project.toml
- src/SurfaceFluxes.jl
Makes it consistent with the dycore paper. Also bumps minor version as it is behavior changing.
----
> change sensible heat flux
